version: '3'

services:
  trendy:
    image: trendy
    build:
      context: .
      dockerfile: Trendy/Dockerfile
    depends_on:
      - mssql
      - mongodb
  mongodb:
    image: mongo
    ports:
      - 27017:27017
  mssql:
    image: microsoft/mssql-server-linux:latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "yourStrong(!)Password"
      MSSQL_PID: "Standard"
    ports: 
      - 1433:1433
    